export const projectsList = [
  {
    title: "Portfolio",
    picture: "portfolio.png",
    github: "https://github.com/pcarillion/portfolioV2",
    tech: ["Next", "React", "TailwindCSS", "Framer Motion"],
    description: "Mon portfolio 2024",
    url: "/",
    date: "2024",
    gallery: ["portfolio.png"],
  },
  {
    title: "Sudfa Media",
    picture: "sudfa.png",
    github: "https://github.com/pcarillion/sudfa-media-next",
    tech: [
      "v1 Gatsby",
      "v2 Next",
      "React",
      "TailwindCSS",
      "v1 Contentful / v2 PayloadJS",
    ],
    description:
      "Sudfa est un petit media franco-soudanais. J'ai designé, conçu et développé le site seul.",
    url: "https://sudfa-media.com/",
    date: "v1 2020, v2 2024",
    gallery: ["sudfa2.png", "sudfa3.png"],
  },
  {
    title: "Entourage Pro",
    picture: "entouragepro.png",
    github: "https://github.com/ReseauEntourage/entourage-job-front",
    tech: ["Next", "React", "Node", "NestJS"],
    description:
      "Dans une squad de 4 dont 2 développeurs, 1 PO et 1 UX, j'ai travaillé pendant 2 ans sur cette plateforme de réinsertion professionnelle pour les plus précaires.",
    url: "entourage-pro.fr",
    date: "2022/2024",
    gallery: ["entouragepro2.png", "entouragepro3.png"],
  },
  {
    title: "Optedif",
    picture: "optedif.png",
    tech: ["Next", "React", "Node", "ExpressJS"],
    description:
      "Dans une squad de 3 développeurs et 1 DevOps, je travaille comme consultant pour aider à l'amélioration des process, l'implémentation de tests, l'optimisation du code et le respect des normes de sécurité.",
    url: "https://fr.optedif-formation.fr/",
    date: "2022, 2024",
    gallery: ["optedif.png"],
    github: null,
  },
  {
    title: "Sodexo",
    picture: "sodexo.png",
    tech: ["Next", "React", "Node", "HapiJS"],
    description:
      "Dans une squad de 6 développeurs, 1 PO, 1 QA et 1 UX, j'ai travaillé comme dev fullstack sur la maintenance d'un portail client Sodexo en 4 langues.",
    date: "2021/2022",
    gallery: ["sodexo.png"],
    url: null,
    github: null,
  },
  {
    title: "Stoff",
    picture: "stoff.png",
    tech: ["Gatsby", "React", "Contentful", "Stripe"],
    description:
      "Pour une revue de sciences humaines, j'ai développé une version numérique avec un mini e-commerce pour commander la version papier.",
    url: "https://www.stoff.fr/",
    date: "2021",
    gallery: ["stoff2.png", "stoff3.png"],
    github: null,
  },
  {
    title: "Ringover",
    picture: "ringover.png",
    tech: ["VanillaJS", "PHP"],
    description:
      "Dans une squad 2 développeurs, j'ai travaillé sur la maintenance et le développement de ce site dans son ancienne version de 2020. La version aujourd'hui en ligne a beaucoup évolué",
    url: "https://www.ringover.fr/",
    date: "2020/2021",
    gallery: ["ringover2.png"],
    github: null,
  },
  {
    title: "Meet by Ringover",
    picture: "ringovermeet.png",
    tech: ["React"],
    description:
      "Pour Ringover, j'ai travaillé à la maintenance du frontend d'une appli de visioconférence.",
    gallery: ["ringovermeet.png"],
    date: "2020/2021",
    url: null,
    github: null,
  },
  {
    title: "MP Site Vitrine",
    picture: "MP.png",
    tech: ["React"],
    description:
      "Dans le cadre d'une collaboration avec une designeuse, nous avions proposé un site vitrine pour montrer notre travail.",
    gallery: ["MP2.png", "MP3.png", "MP4.png"],
    date: "2020",
    url: null,
    github: null,
  },
  {
    title: "Women in War Publications",
    picture: "womeninwar.png",
    tech: ["Gatsby", "React", "Contentful"],
    description:
      "Pour l'association Femaid / Women in war, j'ai développé la version numérique d'un livre de témoignages de femmes dans les pays en guerre pendant le Covid.",
    url: "https://womeninwarpublications.org/",
    gallery: ["womeninwar.png"],
    date: "2021",
    github: null,
  },
  {
    title: "Thomas Jardin Photographie",
    picture: "thomasjardin.png",
    tech: ["React"],
    description:
      "Pour un photographe, j'ai développé un porfolio. Aujourd'hui, le site n'est plus en ligne.",
    gallery: ["thomasjardin-big.png"],
    date: "2020",
    url: null,
    github: null,
  },
  {
    title: "Portfolio v1",
    picture: "portfolioV1.png",
    tech: ["React"],
    description: "Mon premier porfolio en sortant d'études",
    gallery: ["portfolioV12.png"],
    date: "2020",
    url: null,
    github: null,
  },
] as const;
